
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sebas
 */
public class juego extends javax.swing.JFrame {

    /**
     * Creates new form juego
     */
 
    
    //Array de personajes que elige uno aleatorio
    
       Random aleatorio=new Random();
         String[] personajes ={"Batman", "Link","Harry","Woody","Minnie","Spiderman","Daisy","Mario","Elsa","Crash","Naruto","Timón" };
        
     int p=aleatorio.nextInt(personajes.length);
     
     
    
    
    public juego() {
        initComponents();
        
        
        //Método para que la ventana salga en el centro de la pantalla
        this.setLocationRelativeTo(null);
        
      //Imprime el nombre del personaje elegido por consola
    System.out.println(" El personaje será " + personajes[p]); 
        
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        Link = new javax.swing.JLabel();
        Batman = new javax.swing.JLabel();
        Harry = new javax.swing.JLabel();
        Woody = new javax.swing.JLabel();
        Minnie = new javax.swing.JLabel();
        Spiderman = new javax.swing.JLabel();
        Daisy = new javax.swing.JLabel();
        Mario = new javax.swing.JLabel();
        Elsa = new javax.swing.JLabel();
        Crash = new javax.swing.JLabel();
        Naruto = new javax.swing.JLabel();
        Timon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pregunta1 = new javax.swing.JButton();
        pregunta2 = new javax.swing.JButton();
        pregunta4 = new javax.swing.JButton();
        pregunta5 = new javax.swing.JButton();
        pregunta3 = new javax.swing.JButton();
        pregunta6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAdivinar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 300));
        setPreferredSize(new java.awt.Dimension(705, 630));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        Link.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/link.jpeg"))); // NOI18N
        Link.setText("jLabel2");
        Link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LinkMousePressed(evt);
            }
        });

        Batman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/batman.jpg"))); // NOI18N
        Batman.setText("Batman");
        Batman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatmanMouseClicked(evt);
            }
        });

        Harry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/harry.jpeg"))); // NOI18N
        Harry.setText("jLabel3");
        Harry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HarryMouseClicked(evt);
            }
        });

        Woody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/woody.jpg"))); // NOI18N
        Woody.setText("jLabel4");
        Woody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WoodyMouseClicked(evt);
            }
        });

        Minnie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minnie.png"))); // NOI18N
        Minnie.setText("jLabel5");
        Minnie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinnieMouseClicked(evt);
            }
        });

        Spiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spider.jpg"))); // NOI18N
        Spiderman.setText("jLabel6");
        Spiderman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpidermanMouseClicked(evt);
            }
        });

        Daisy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Daisy.jpg"))); // NOI18N
        Daisy.setText("jLabel7");
        Daisy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DaisyMouseClicked(evt);
            }
        });

        Mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mario.jpg"))); // NOI18N
        Mario.setText("jLabel8");
        Mario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarioMouseClicked(evt);
            }
        });

        Elsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Elsa.jpg"))); // NOI18N
        Elsa.setText("jLabel9");
        Elsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElsaMouseClicked(evt);
            }
        });

        Crash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Crash.jpg"))); // NOI18N
        Crash.setText("jLabel1");
        Crash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrashMouseClicked(evt);
            }
        });

        Naruto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Naruto.jpg"))); // NOI18N
        Naruto.setText("jLabel2");
        Naruto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NarutoMouseClicked(evt);
            }
        });

        Timon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Timon.jpg"))); // NOI18N
        Timon.setText("jLabel3");
        Timon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Batman, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Woody, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Daisy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crash, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Naruto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minnie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Link, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Spiderman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Harry, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(Elsa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Timon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batman, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Link)
                    .addComponent(Harry, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Woody)
                    .addComponent(Minnie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Spiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Daisy)
                    .addComponent(Mario)
                    .addComponent(Elsa))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Crash)
                            .addComponent(Naruto)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Timon)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 530);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        pregunta1.setText("¿LLeva gorro o sombrero?");
        pregunta1.setBorder(new javax.swing.border.MatteBorder(null));
        pregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta1ActionPerformed(evt);
            }
        });

        pregunta2.setText("¿Es una chica?");
        pregunta2.setBorder(new javax.swing.border.MatteBorder(null));
        pregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta2ActionPerformed(evt);
            }
        });

        pregunta4.setText("¿Es rubio/a?");
        pregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta4ActionPerformed(evt);
            }
        });

        pregunta5.setText("¿Lleva un lazo?");
        pregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta5ActionPerformed(evt);
            }
        });

        pregunta3.setText("¿Leva máscara?");
        pregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta3ActionPerformed(evt);
            }
        });

        pregunta6.setText("¿Es un animal?");
        pregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pregunta6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(pregunta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pregunta2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(pregunta3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(pregunta5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(490, 0, 220, 610);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        btnAdivinar.setBackground(new java.awt.Color(51, 51, 51));
        btnAdivinar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdivinar.setText("Adivinar");
        btnAdivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnAdivinar)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAdivinar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 530, 490, 80);

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 102));

        jMenu5.setText("Menú");

        jMenuItem1.setText("Reiniciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Ver puntuaciones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Volver a inicio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Variable para imagen del personaje
    
    private boolean linkimg=false;
    
    private void LinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkMouseClicked
        // Con el condidional hacemos que aparezca tachado o no al hacer clic
 if(linkimg){
     //Si es false será la imagen 1 (Sin tachar)
            Link.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/link.jpeg")));
            linkimg=false;
        }else{
     //Si es true la imagen será la tachada
            Link.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/link2.jpeg")));
      linkimg=true;
        }        
    }//GEN-LAST:event_LinkMouseClicked

//TODOS LOS PERSONAJES TENDRÁN EL MISMO CÓDIGO PARA QUITAR O PONER EL TACHADO
    
    
    private boolean batmanimg=false;
    private void BatmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatmanMouseClicked
        // TODO add your handling code here:
        
 if(batmanimg){
            Batman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/batman.jpg")));
            batmanimg=false;
        }else{
            Batman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/batman2.jpg")));
        batmanimg=true;
        }        
    }//GEN-LAST:event_BatmanMouseClicked

    private boolean harryimg=false;
    private void HarryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HarryMouseClicked
        // TODO add your handling code here:
        if(harryimg){
            Harry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/harry.jpeg")));
           harryimg=false;
        }else{
            Harry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/harry2.jpeg")));
       harryimg=true;
        }
    }//GEN-LAST:event_HarryMouseClicked

    
    
    
    //Boton para saber si lleva gorro o sombrero
    private void pregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta1ActionPerformed
    //Si el personaje corresponde a esos carácteres dirá que si, si no dirá que no    
     
    if (personajes[p].equals("Link") || personajes[p].equals("Woody") || personajes[p].equals("Mario")) {
        
      
     JOptionPane.showMessageDialog(null, "Si, el personaje  lleva gorro o sombrero","",JOptionPane.PLAIN_MESSAGE);
      
       
    }else {
      JOptionPane.showMessageDialog(null, "No, el personaje no lleva gorro o sombrero","",JOptionPane.PLAIN_MESSAGE);
       
       
    }
     // En todos lo botones de preguntas se introduce el mismo código cambiando personajes
    }//GEN-LAST:event_pregunta1ActionPerformed

 
   // Clase con variables de respuestas correctas e incorrectas
    public class Partidas{
        public static int correctas=0;
        public static int incorrectas=0;
    }
    
    //Boton adivinar
    private void btnAdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarActionPerformed
   
    //Panel para escribir el nombre
        String respuesta = JOptionPane.showInputDialog(null,"Escribe el nombre del personaje","",JOptionPane.PLAIN_MESSAGE);
        
        //Con este método nos permitirá cancelar si que cuente como incorrrecto
    if(respuesta!=null){
        
        //Si el personaje introducido coincide con el elegido nos saltará el mensaje "Correcto"
        if(respuesta.equalsIgnoreCase(personajes[p])){
           
        JOptionPane.showMessageDialog(null,"CORRECTO","",JOptionPane.PLAIN_MESSAGE);
       
        //Si la respuesta es correcta el juego se reiniciará
        this.setVisible(false);
        juego reiniciar=new juego();
        reiniciar.setVisible(true);
        //Contador de rspuestas correctas
        Partidas.correctas++;
    }else{
            //Si el personaje introducido no es el elegido saltará el mensaje "Incorrecto"
        JOptionPane.showMessageDialog(null,"INCORRECTO","",JOptionPane.PLAIN_MESSAGE);
      
        //Contador de palabras incorrectas
        Partidas.incorrectas++;
    }
    }
  
        
    }//GEN-LAST:event_btnAdivinarActionPerformed
//No usado
    private void LinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkMousePressed
       
    }//GEN-LAST:event_LinkMousePressed

    private void pregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta2ActionPerformed
        
        
         if (personajes[p].equals("Minnie") || personajes[p].equals("Daisy") || personajes[p].equals("Elsa")) {
        
      JOptionPane.showMessageDialog(null, "Si, el personaje es una chica", "", JOptionPane.PLAIN_MESSAGE);
    }else{
      
         JOptionPane.showMessageDialog(null, "No, el personaje no es una chica", "", JOptionPane.PLAIN_MESSAGE);
    }
        
    }//GEN-LAST:event_pregunta2ActionPerformed

    private void pregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta3ActionPerformed
        
        if(personajes[p].equals("Batman")|| personajes[p].equals("Spiderman")){
            JOptionPane.showMessageDialog(null,"Si, el personaje lleva máscara","",JOptionPane.PLAIN_MESSAGE);
          
        }else{
            JOptionPane.showMessageDialog(null,"No, el personaje no lleva máscara","",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_pregunta3ActionPerformed

    private void pregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta4ActionPerformed
       
        if(personajes[p].equals("Link") ||personajes[p].equals("Elsa") || personajes[p].equals("Naruto") ){
            JOptionPane.showMessageDialog(null,"Si, el personaje es rubio/a","",JOptionPane.PLAIN_MESSAGE);
          
        }else{
            JOptionPane.showMessageDialog(null,"No, el personaje no es rubio/a","",JOptionPane.PLAIN_MESSAGE);
        }
            
    }//GEN-LAST:event_pregunta4ActionPerformed

    private void pregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta5ActionPerformed
        
        if(personajes[p].equals("Daisy")|| personajes[p].equals("Minnie")){
            JOptionPane.showMessageDialog(null,"Si, el personaje lleva un lazo","",JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"No,el personaje no lleva un lazo","",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_pregunta5ActionPerformed

    private void pregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta6ActionPerformed
        
        if(personajes[p].equals("Minnie")||personajes[p].equals("Daisy")|| personajes[p].equals("Crash")||personajes[p].equals("Timón")){
            JOptionPane.showMessageDialog(null, "Si, el personaje es un animal","",JOptionPane.PLAIN_MESSAGE);
        
    }else{
            JOptionPane.showMessageDialog(null,"No,el personaje no es un animal","",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_pregunta6ActionPerformed

    private boolean woodyimg=false;
    private void WoodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WoodyMouseClicked
       
        if(woodyimg){
        Woody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/woody.jpg")));
        woodyimg=false;
        }else{
            
             Woody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/woody2.jpg")));
        woodyimg=true;
        }
    }//GEN-LAST:event_WoodyMouseClicked


    private boolean minnieimg=false;
    private void MinnieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinnieMouseClicked
        
        if(minnieimg){
           Minnie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minnie.png")));
            minnieimg=false;
        }else{
            Minnie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minnie2.png")));
       minnieimg=true;
        }
    }//GEN-LAST:event_MinnieMouseClicked

    
    private boolean spidermanimg=false;
    private void SpidermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpidermanMouseClicked
       
        
          if (spidermanimg) {
       
        Spiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spider.jpg")));
        spidermanimg = false; 
    } else {
        
        Spiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spider2.jpg")));
        spidermanimg = true; 
    
}
        
    }//GEN-LAST:event_SpidermanMouseClicked

    private boolean daisyimg=false;
    private void DaisyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaisyMouseClicked
        
       if(daisyimg){
            Daisy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Daisy.jpg")));
          daisyimg=false;
        }else{
            Daisy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Daisy2.jpg")));
        daisyimg=true;
        }
       
       
    }//GEN-LAST:event_DaisyMouseClicked

    private boolean marioimg=false;
    private void MarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarioMouseClicked
        
       
        if(marioimg){
            Mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mario.jpg")));
           marioimg=false;
        }else{
            Mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mario2.jpg")));
        marioimg=true;
        }
    }//GEN-LAST:event_MarioMouseClicked

    private boolean elsaimg=false;
    private void ElsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElsaMouseClicked
       
         if(elsaimg){
            Elsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Elsa.jpg")));
            elsaimg=false;
        }else{
            Elsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Elsa2.jpg")));
        elsaimg=true;
        }
    }//GEN-LAST:event_ElsaMouseClicked

    
    
    
    
    private boolean crashimg=false;
    private void CrashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrashMouseClicked
        
        if(crashimg){
            Crash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Crash.jpg")));
            crashimg=false;
        }else{
            Crash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Crash2.jpg")));
        crashimg=true;
        }
    }//GEN-LAST:event_CrashMouseClicked

    private boolean narutoimg=false;
    private void NarutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NarutoMouseClicked
        
         if(narutoimg){
            Naruto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Naruto.jpg")));
            narutoimg=false;
        }else{
            Naruto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Naruto2.jpg")));
       narutoimg=true;
        }
    }//GEN-LAST:event_NarutoMouseClicked

    private boolean timonimg=false;
    private void TimonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimonMouseClicked
        
         if(timonimg){
            Timon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Timon.jpg")));
            timonimg=false;
        }else{
            Timon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Timon2.jpg")));
        timonimg=true;
        }
    }//GEN-LAST:event_TimonMouseClicked

    //Botón Reiniciar
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  
        
        this.setVisible(false);
        juego reiniciar=new juego();
        reiniciar.setVisible(true);        
        
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Botón para ver puntuaciones
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "Respuestas correctas: " + Partidas.correctas + "\nRespuestas incorrectas: " + Partidas.incorrectas,"",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //Boton para volver a inicio
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      
        
          this.setVisible(false);
        inicio irainicio=new inicio();
       irainicio.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Batman;
    private javax.swing.JLabel Crash;
    private javax.swing.JLabel Daisy;
    private javax.swing.JLabel Elsa;
    private javax.swing.JLabel Harry;
    private javax.swing.JLabel Link;
    private javax.swing.JLabel Mario;
    private javax.swing.JLabel Minnie;
    private javax.swing.JLabel Naruto;
    private javax.swing.JLabel Spiderman;
    private javax.swing.JLabel Timon;
    private javax.swing.JLabel Woody;
    private javax.swing.JButton btnAdivinar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton pregunta1;
    private javax.swing.JButton pregunta2;
    private javax.swing.JButton pregunta3;
    private javax.swing.JButton pregunta4;
    private javax.swing.JButton pregunta5;
    private javax.swing.JButton pregunta6;
    // End of variables declaration//GEN-END:variables
}
